TOPDIR = ..
PROG = cbench
SRCS = cbench.c
EXTRA_OBJS = ${TOPDIR}/io/libmaple-io.a
EXTRA_CFLAGS = -O2 -fno-strict-aliasing -Wall -g -I/usr/local/include -I/home/btw/local/include
EXTRA_LDFLAGS = -L/home/btw/local/lib -L/usr/local/lib -lev

-include ${TOPDIR}/Makefile.comm