TOPDIR = ..
POF_VERSION ?= POFSwitch_VERSION_1_1_9
EXTRA_CFLAGS = -g -O2 -Wall -DPOFSWITCH_VERSION_NO=${POF_VERSION}
SRCS = xswitch.c flow_table.c match.c action.c msg.c
LIB = libxswitch.a

include ${TOPDIR}/Makefile.comm
